---
title: "Latex assignment"
author: "Chaman Preet Kaur"
date: "February 04, 2015"
output: pdf_document
---
The Scenario
====================================================================
You are craving for chocolate cake and want to bake it at home. You drive to safeway to find a pan and there are two of them available. A square cake pan and a circular cake pan both with the same height. The side of the square pan is same as the diameter of the circular pan. How do you decide which pan should you buy in case you want to have more cake. 

The Solution
====================================================================
In order to decide on the pan, we compare the volumes of cake baked in a square pan and the circular pan. 


Calculations
====================================================================
Volume of square pan is calculated as follows:
$$ a^2 h\ $$ 

In this case

''a'' = 9 inches (length of side)

''h'' = 2 inches (depth)

Volume of circular cake pan is calculated as follows:
$$ \pi r^2 h\ $$

In this case

''r'' = 4.5 inches radius of circular face

''h'' = 2 inches height


```{r, echo=FALSE}
a <- 9
h <- 2
r <- 4.5
volume_of_square_pan <- a^2* h
volume_of_circular_pan <- pi* r^2*h
vol <- c(volume_of_square_pan, volume_of_circular_pan)
heights <- c(2,2)
plot (vol, heights , main="Scatterplot", 
      xlab="volume ", ylab=" height ")

```


Conclusion
====================================================================
From the plots and calculation it is evident that volume of a square pan (`r volume_of_square_pan` cubic inches) is more than a circular pan (`r round(volume_of_circular_pan,1)` cubic inches). Hence, in case you want to have a bigger cake, do not hesitate to choose the square cake pan.

